# Generated by Django 3.0.5 on 2020-04-13 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('buying_price', models.FloatField()),
                ('buying_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
